                                     Iris species prediction
                                
                                
                                


Introduction : In this project we are going to predict the species of Iris flower


Step-1: Importing Libraries

In [1]:
import numpy as np

import pandas as pd 

Step-2: Gathering data

In [2]:
s=pd.read_csv("/home/silpa/Downloads/Iris.csv")


step-3: Assigning input and output 

In [3]:
x=s.iloc[:,1:5].values

y=s.iloc[:,-1].values

Step-4: Modelling

In [4]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=40)

Normalization

In [5]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

scaler.fit(x_train)

StandardScaler()

x_train=scaler.transform(x_train)

x_test=scaler.transform(x_test)

In [6]:

from sklearn.neighbors import KNeighborsClassifier

classifier=KNeighborsClassifier(n_neighbors=5)

classifier.fit(x_train,y_train)

KNeighborsClassifier()

y_pred=classifier.predict(x_test)

print(classifier.predict([[5.1,3.5,1.4,0.2]]))

['Iris-virginica']


In [7]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_pred)
print(result)
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

[[16  0  0]
 [ 0 13  1]
 [ 0  0 15]]
0.9777777777777777


In [8]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      0.93      0.96        14
 Iris-virginica       0.94      1.00      0.97        15

       accuracy                           0.98        45
      macro avg       0.98      0.98      0.98        45
   weighted avg       0.98      0.98      0.98        45

